services:
  db:
    container_name: mysql-bun
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bun-mysql

  app:
    container_name: app
    image: oven/bun:distroless
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    tty: true
    networks:
      - bun-mysql
    depends_on:
      - db

networks:
  bun-mysql:
    driver: bridge

volumes:
  mysql-data:
